services:
  server:
    container_name: server
    environment:
      - FLASK_APP=server:create_app()
      - FLASK_DEBUG=1
    volumes:
      - .:/backend
    command: flask run --host=0.0.0.0
  redis:
    container_name: redis
    image: redislabs/redismod
    ports:
       - '6379:6379' 